services:
  node:
    image: "node:current"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes: 
      - ./:/home/node/app
    command: bash -c "npm install --include=dev && npm run build"
  web:
    image: "nginx"
    network:
      - "80:80"
      - "443:443"
    volumes: 
      - ./dist:/usr/share/nginx/html
